version: '3.8'

services:
  ros-dev:
    image: ros-dev-image:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    container_name: ros-dev-container
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=${DISPLAY}
      - TERM=xterm-256color
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/dri:/dev/dri:ro
      - /home/pyae/projects/ros-playground:/home/developer/ros-playground
    network_mode: host
    ipc: host
